version: '3'

services:
  mysql:
    image: mysql:5.7.30
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
      MYSQL_DATABASE: food_srv
    container_name: mysql-container